# Use a lightweight base image (assuming your base image has Java installed)
FROM cerberus237/adaptable-teastore-image:latest

# Copy the local Java artifact into the container
COPY ./siphonix-app.jar /usr/local/tomcat/bin/siphonix.jar

# Run the compiled Java application (using JSON array format to prevent OS signal issues)
CMD ["sh", "-c", "java -jar /usr/local/tomcat/bin/siphonix.jar & /usr/local/tomcat/bin/start.sh && /usr/local/tomcat/bin/catalina.sh run"]