FROM cerberus237/adaptable-teastore-image:latest

ARG SIPHONIX
COPY ${SIPHONIX} /usr/local/tomcat/bin/siphonix.jar

CMD ["sh", "-c", "java -jar /usr/local/tomcat/bin/siphonix.jar & /usr/local/tomcat/bin/start.sh && /usr/local/tomcat/bin/catalina.sh run"]
